### ISSUE TITLE
What is amplitude -inf dBfs ?

### ISSUE THREAD

**Issue by engantonio** [greatscottgadgets/hackrf#1121]
I am trying to generate a spoofer with hackRF but when i run it appear : 

 5.2 MiB / 1.006 sec =  5.2 MiB/second, amplitude -inf dBfs
 5.2 MiB / 1.006 sec =  5.2 MiB/second, amplitude -inf dBfs
 5.2 MiB / 1.007 sec =  5.2 MiB/second, amplitude -inf dBfs
 5.2 MiB / 1.009 sec =  5.2 MiB/second, amplitude -inf dBfs

Please what is "amplitude -inf dBfs" ?

**Comment by martinling** [comment]
It's a bug, already filed as #902. The amplitude isn't calculated during TX. There is a PR to fix it at #1116 which I need to review.

**Comment by engantonio** [comment]
But 

> It's a bug, already filed as #902. The amplitude isn't calculated during TX. There is a PR to fix it at #1116 which I need to review.

But how can i solve this ?

**Comment by martinling** [comment]
What do you need to solve? The message doesn't mean it's not transmitting. It just displays `-inf` because `hackrf_transfer` doesn't calculate the amplitude of the sample stream during TX. That amplitude display feature was intended to help with adjusting RX gains when receiving a signal. If you're transmitting a signal, the amplitude of the TX sample stream is whatever you generated it to be.

**Comment by engantonio** [comment]
Both generating in linux or in windows the spoofer is not working.... but its transmiting...

**Comment by ardyitjen** [comment]
is there any update? i got sampe problem with portapack h2

**Comment by martinling** [comment]
The `-inf dBfs` message was fixed in #1116 and that fix was shipped in 2022.09.1 and subsequent releases of the host tools. In any case, this message is almost certainly nothing to do with your problem. It does not mean nothing is being transmitted, it was just a display bug.
