### ISSUE TITLE
Wrong baseband filter bandwidth in libhackrf?

### ISSUE THREAD

**Issue by glv2** [greatscottgadgets/hackrf#1129]
The ```max2837_ft``` variable in "host/libhackrf/src/hackrf.c" has 2.5 MHz as second baseband filter bandwidth, however the datasheet for the MAX2837 chip has 2.25 MHz (see page 5 in https://pdf1.alldatasheet.com/datasheet-pdf/view/298297/MAXIM/MAX2837.html).

Is it a typo in the code, or is there a reason?

**Comment by mossmann** [comment]
It is consistent with the firmware and `hackrf_transfer`. The original discrepancy is in the MAX2837 documentation. See page 5 vs. page 20 in the latest version of the data sheet: https://datasheets.maximintegrated.com/en/ds/MAX2837.pdf

Originally the register documentation was in a separate document, but it has since been incorporated into the data sheet.

I believe that the actual 3 dB bandwidth of the filter is closer to 2.5 MHz than to 2.25 MHz.
