### ISSUE TITLE
[Bug Report]: `hackrf_transfer` misbehaves with `-H -n 393216` and `-c` or `-t`

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/hackrf#1164]
### What type of issue is this?

permanent - occurring repeatedly

### What issue are you facing?

When `hackrf_transfer` is configured to wait for a trigger and then transmit a small number of samples (fewer than 393217), the "Waiting for sync" output does not appear. During this wait the command cannot be terminated with Ctrl-C.

### What are the steps to reproduce this?

- leave trigger input unconnected
- `hackrf_transfer -c 0 -H -n 393216`
- type Ctrl-C

**Comment by martinling** [comment]
What's happening here is:

- All samples are used up in the preload phase.
- `hackrf_transfer` proceeds directly to running `hackrf_await_tx_flush`, which would be correct if we still expect TX to happen.
- When you press Ctrl-C, `hackrf_transfer` is blocked in `hackrf_await_tx_flush`.

This seems like a fundamental issue with the API introduced by #1139, because we don't provide any way to interrupt that function if you no longer want to continue waiting.
