### ISSUE TITLE
[Question]: How to enable Bias Tee in HackRF One to power an antenna or amplifier?

### ISSUE THREAD

**Issue by alexeysirenko** [greatscottgadgets/hackrf#1228]
### What would you like to know?

Hello. I was unable to find a way to power an LNA using HackRF built-in ability to supply 3.3V over the coax cable. For instance, with RTL-SDR dongles it can be done simply using a bash script. With Hack RF it is not that easy. I found a couple of, as I thought, solutions, based on the `hackrf_transfer` utility (I used the one that comes with the PothosSDR software):
`hackrf_transfer -p 1` - it should have enabled the power, but this command can not be executed without extra parameters, that, if applied, start transferring data to/from the device and, since the device is busy, it no longer can be used as a source in SDR# or other similar software. Is there a workaround? For SDR# in particular. Thank you

P.S. I am using SDR# because of the plugins, I've heard that some other tools like SDR++ have an `enable bias tee` checkbox available for the HackRF, but if the only option would be to move to another software utility, I'll have to buy some other SDR receiver instead, unfortunately, so I am hoping for a solution suitable for SDR# too

P.P.S. This is the solution that I found, but it does not work:
https://www.reddit.com/r/RTLSDR/comments/8om4tg/biast_for_hackrf_on_sdr/
This is what I receive when I follow the instructions:
```
hackrf_transfer -p 1

specify one of: -t, -c, -r, -w

Usage:

-h # this help

[-d serial_number] # Serial number of desired HackRF.

-r <filename> # Receive data into file (use '-' for stdout).

-t <filename> # Transmit data from file (use '-' for stdin).

-w # Receive data into file with WAV header and automatic name.

# This is for SDR# compatibility and may not work with other software.

[-f freq_hz] # Frequency in Hz [0MHz to 7250MHz].

[-i if_freq_hz] # Intermediate Frequency (IF) in Hz [2150MHz to 2750MHz].

[-o lo_freq_hz] # Front-end Local Oscillator (LO) frequency in Hz [84MHz to 5400MHz].

[-m image_reject] # Image rejection filter selection, 0=bypass, 1=low pass, 2=high pass.

[-a amp_enable] # RX/TX RF amplifier 1=Enable, 0=Disable.

[-p antenna_enable] # Antenna port power, 1=Enable, 0=Disable.

[-l gain_db] # RX LNA (IF) gain, 0-40dB, 8dB steps

[-g gain_db] # RX VGA (baseband) gain, 0-62dB, 2dB steps

[-x gain_db] # TX VGA (IF) gain, 0-47dB, 1dB steps

[-s sample_rate_hz] # Sample rate in Hz (2-20MHz, default 10MHz).

[-n num_samples] # Number of samples to transfer (default is unlimited).

[-c amplitude] # CW signal source mode, amplitude 0-127 (DC value to DAC).

[-R] # Repeat TX mode (default is off)

[-b baseband_filter_bw_hz] # Set baseband filter bandwidth in Hz.

Possible values: 1.75/2.5/3.5/5/5.5/6/7/8/9/10/12/14/15/20/24/28MHz, default <= 0.75 * sample_rate_hz.

[-C ppm] # Set Internal crystal clock error in ppm.
```

P.P.P.S. I assume that there is a `hackrf_set_antenna_enable(1: uint)` function in hackrf.dll which is called by the `hackrf_transfer` util. So the best way would have been to have a checkbox added to the SDR# that, apparently, uses the same library, and when the device is started, calls this function. It is strange that this functionality is not implemented, but I really need the ability to power up an amplifier via bias tee as soon as possible, so a workaround would be fine

**Comment by martinling** [comment]
The `hackrf_transfer` program shows you the usage message because you haven't given it anything to actually do. It's expecting to be given one of the `-r` (RX) `-t` (TX) or `-c` (CW signal generator) options. The `-p` option just makes it turn on the bias tee whilst it does that operation.

As soon as the HackRF leaves TX or RX mode, the firmware turns the bias tee off. I think that when that advice on Reddit was written, that user must have been using some old firmware version which failed to turn the bias tee off.

The right way for this to work is that SDR# needs to add a checkbox for the bias tee, and call the `hackrf_set_antenna_enable` function. There isn't any way to force it by running a helper program first, because the firmware turns the bias tee off as soon as it goes back to idle mode.

If you need a quick workaround without the hassle of modifying the SDR# UI, I see two options:

- Build your own copy of SDR# from source, adding a call to `hackrf_set_antenna_enable(device, 1)`. The place to put this would be just before wherever it calls `hackrf_start_rx`.

- Build your own copy of the HackRF firmware from source, and add a call to `rf_path_set_antenna(rf_path, 1)`. The place to put this would be in the `RF_PATH_DIRECTION_RX` block in `rf_path_set_direction`.

Either option would force the HackRF to always have the bias tee on when in RX mode.

**Comment by straithe** [comment]
@alexeysirenko it looks like your question has been answered. May I close this issue?

**Comment by alexeysirenko** [comment]
Yes, thank you
