### ISSUE TITLE
Any practical way of doing Equivalent Time Sampling with one or more HackRF Ones?

### ISSUE THREAD

**Issue by espentj** [greatscottgadgets/hackrf#1259]
### What would you like to know?

We are trying to measure pulsed electromagnetic signals in the time-domain for studying EM reflectometry of GHz signals. But the sampling rate of the HackRF is too low to properly digitize the signals. Can we use equivalent time sampling to overcome this problem? And do you know of any practical way of setting up the HackRF One to do it?

**Comment by martinling** [comment]
Interesting question!

As I understand it, equivalent time sampling relies on knowing the offset between a trigger event and the first sample time, to a resolution smaller than that of the sampling clock.

In the case of sequential equivalent time sampling, that's done by starting the sampling clock at a variable delay after the trigger event. Or for random equivalent time sampling, by measuring the delay from the trigger event to the next cycle of an ongoing sample clock.

With the way that clock generation works on HackRF, starting the sample clock at a given instant doesn't seem possible. You can only start sampling on the next cycle of the existing clock. So you would have to use the random equivalent time sampling approach.

You would need an external circuit to detect the trigger event you're looking for. That could be attached to the P9 header, where the analog baseband signal is accessible. The sample clock is available on P28, as is the trigger input.

I think you could build an add-on board that attached to these two headers and would:
  1. detect the trigger event
  2. enable the trigger input, to start sampling on the next clock cycle
  3. measure the time offset between the trigger event and the next clock cycle, to your desired resolution.

Then by accumulating enough similar events with random time offsets, you could build a picture of the events to a high time resolution. The fundamental limitation would be the combined jitter of the whole system.

However, I don't think this actually gains you anything. Because you would be measuring the baseband signal, which has gone through either one or two downconversions from the original GHz inputs, and been put through the baseband low pass filters within the MAX2837, whose bandwidth only goes up to 31MHz at most.

I'm not sure HackRF helps you here. I think you just need a fast oscilloscope.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
