### ISSUE TITLE
banned on discord and can no longer get support

### ISSUE THREAD

**Issue by mrc333777** [greatscottgadgets/hackrf#1319]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

unban me or give me a refund for this hackrf one and yardstick one
only seems fair, i paid around 500 dollars for these 2 devices.

### What outcome actually happened?

i would like this issue to be reviewed by a higher authority other than the one who banned me, she has biased
beliefs.

### What operating systems are you seeing the problem on?

all

### What is the output of ```hackrf_info```?

n/a

### Are you using any third-party software?

no

### Are you using any third-party hardware?

no

**Comment by straithe** [comment]
We do not sell devices directly so any returns you may wish to do would have to be done through your reseller. You are still welcome to support through your reseller. 

You were banned from Discord for disrespectful conduct towards community members and you will not be unbanned because you followed up your ban with harassing and abusive private messages towards me.
