### ISSUE TITLE
Broken timing in hackrf_transfer on OpenBSD, due to SIGALRM being delivered to transfer thread

### ISSUE THREAD

**Issue by bsdmp** [greatscottgadgets/hackrf#1323]
### What type of issue is this?

permanent - occurring repeatedly

### What issue are you facing?

while doing simple `hackrf_transfer -r /dev/null` I face following error

`Couldn't transfer any bytes for one second.`

full log:

```
call hackrf_set_sample_rate(10000000 Hz/10.000 MHz)
call hackrf_set_hw_sync_mode(0)
call hackrf_set_freq(900000000 Hz/900.000 MHz)
Stop with Ctrl-C
 7.9 MiB / 1.006 sec =  7.8 MiB/second, average power -28.5 dBfs
 7.6 MiB / 1.000 sec =  7.6 MiB/second, average power -28.4 dBfs
 7.6 MiB / 2.000 sec =  3.8 MiB/second, average power -28.5 dBfs
 0.0 MiB / 1.000 sec =  0.0 MiB/second, average power -nan dBfs

Couldn't transfer any bytes for one second.

Exiting... hackrf_is_streaming() result: streaming stopped (-1003)
Total time: 5.00616 s
hackrf_stop_rx() done
hackrf_close() done
hackrf_exit() done
fclose() done
exit
```

`v2021.03.1` works fine though, I have done a bisect and it came up to the following commit:

```
a09e9a20ed42567b1fe979ab4db12f9f2590b2a4 is the first bad commit
commit a09e9a20ed42567b1fe979ab4db12f9f2590b2a4
Author: Martin Ling <martin-git@earth.li>
Date:   Fri Aug 5 15:43:25 2022 +0100

    Overhaul timing in hackrf_transfer.

    Rather than using sleep() for 1s at a time, set up an interval timer
    that will fire once per second, and wait in the main loop for either
    this or some other event.

    On POSIX, the timing is set up with setitimer(), which generates a
    SIGALRM signal each time the timer fires. The main loop runs pause() to
    wait for any signal.

    On Windows, the timing is set up using CreateWaitableTimer, which
    provides an event handle that is set each time the timer fires. The main
    loop runs WaitForMultipleObjects() to wait on this and an interrupt
    event.

    The TX and RX callbacks can now stop the main loop immediately when they
    stop streaming. This fixes #1019.

 host/hackrf-tools/src/hackrf_transfer.c | 71 ++++++++++++++++++++++++++++++---
```

### What are the steps to reproduce this?

run `hackrf_transfer -r /dev/null` on `OpenBSD 7.3 GENERIC.MP#1175 amd64` (openbsd current)

### Can you provide any logs? (output, errors, etc.)

```
# hackrf_info
hackrf_info version: 2023.01.1
libhackrf version: 2023.01.1 (0.8)
Found HackRF
Index: 0
Serial number: XXXX
Board ID Number: 2 (HackRF One)
Firmware Version: 2023.01.1 (API:1.07)
Part ID Number: XXX XXX
Hardware Revision: older than r6
Hardware supported by installed firmware:
    HackRF One
```

**Comment by martinling** [comment]
Thanks for taking the time to bisect this to my commit.

OpenBSD is not a platform we actively develop and test on, and I don't personally have a system available to reproduce this at the moment, so all I have to go on for the moment is the symptoms in your logs.

From those symptoms, I'm not sure what's going wrong. In theory, the timing code introduced in this commit should work on any POSIX-compatible system, and indeed I think this particular API originated in BSD in the first place.

Something fishy is definitely happening though, because after setting up the interval timer and `SIGALRM`, the first two messages happen on time, but the third is a whole second late:

```
 7.9 MiB / 1.006 sec
 7.6 MiB / 1.000 sec
 7.6 MiB / 2.000 sec
```

If the OS is implementing the timer and signals correctly I don't understand how that can happen, given what `hackrf_transfer` is doing at that point. Since you're not running with `-B` to enable `display_stats`, there's hardly anything happening in the main loop - all it does is call `pause` to wait for the signal, `gettimeofday` to see how much time has passed, and then `fprintf` to write the message. The values in the message all come from global variables.

So either the signal is arriving a whole second late, or the main thread is getting blocked for a whole second. But I don't see what could be blocking it. The USB I/O is all happening in a separate thread.

I wonder if the whole process is hanging for a second, due to some USB I/O issue perhaps? It may be that this commit merely makes an existing problem now cause an error, when it previously didn't.

**Comment by martinling** [comment]
Ah, that makes sense, and I think your testing with that change confirms that must be what's going on - the signal is sometimes delivered to the transfer thread rather than the main thread.

I'm not sure modifying libhackrf like that is the right fix, though. It works for the specific case of `SIGALRM` as used by `hackrf_transfer`, but other programs may run into this issue with other signals.

I think ideally, libraries should not be messing with decisions about signals. As a process-wide issue, that's normally a matter for the author of the overall program. However, since libhackrf creates its own threads behind the scenes, I guess we have to make the decisions about how we configure those threads.

A better solution might be for libhackrf to mask *all* signals for its internal threads, which should ensure they always stay out of the way of whatever signal handling the program is doing. There may be some downside to this I haven't thought of, though.

**Comment by martinling** [comment]
That looks reasonable to me. Could you submit it as a pull request please?
