### ISSUE TITLE
frequency switch

### ISSUE THREAD

**Issue by ozzyys** [greatscottgadgets/hackrf#1362]
### What would you like to know?

Hello, I'm thinking of buying a Hackrf one. When I look at its features, I think it can meet my needs, but I have only one question in my mind. In the system I designed, the user enters the frequencies he wants to measure and then receives the current data from the receiver. Of course, the transmitter must be active while it receives the data (in fact, it is always active. It works continuously).

In the system I have already designed, when different frequencies are entered, the board in my hand successfully makes "frequency switch" and takes measurements at different frequencies and does this continuously. 

Since I want to reduce the cost of the system, I want to use Hackrf one. I read the documents and watched the videos on the sites I mentioned in sources [1] and [2]. But I couldn't find much information about my subject. 

My main question is: Can Hackrf one switch frequency? What I'm really curious about is, if it can do this, at what speed? If there is a document or article about this, I would be very grateful if you could share it with me.

For example, the card I have can scan from 1GHz to 6GHz in 500MHz steps in 5 seconds.

[1] https://greatscottgadgets.com/hackrf/one/
[2] https://hackrf.readthedocs.io/en/latest/index.html

**Comment by martinling** [comment]
I have good news for you, then: the HackRF One can scan 1MHz to 6GHz in 10MHz steps in 0.75 seconds.

This is enabled by a specific sweep mode in the firmware, in which the device takes control of the retuning and sample collection to achieve the necessary timing requirements. The host receives a stream of data containing samples for each configured frequency step in turn.

This mode is usually invoked from the `hackrf_sweep` command line tool. That tool collects 8192 samples at each 10MHz step, then computes FFTs from each of these batches of samples, and uses these to report power in each frequency bin across the whole sweep range, effectively turning the HackRF One into a spectrum analyzer. There are some GUI programs like [QSpectrumAnalyzer](https://github.com/xmikos/qspectrumanalyzer) that can be used with this feature.

If you want to do other things with the collected samples rather than just take an FFT though, or use different frequency steps, or collect for longer at each frequency, then you can do this in your own program via the libhackrf API.
