### ISSUE TITLE
GPS position drift

### ISSUE THREAD

**Issue by joelmatejka** [greatscottgadgets/hackrf#1371]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

Get fix in a few minutes and simulate precise location (+- a few meters at maximum).

### What outcome actually happened?

TLDR: gps-sdr-sim -> HackRF -> ublox GPS: drifts for dozens of meters in static and also dynamic mode, sometimes looses fix

## Setup

Sorry for quite a lot maybe not relevant information...

I tried multiple configurations. But always similar scenario:

- Schematic
  ```
  ┌─────────────┐    ┌─────────────────┐    ┌────────────┐  sma cable  ┌─────────┐ ┌─────────┐ ┌────────┐  ┌────────────────────┐    ┌───────────────┐
  │ gps-sdr-sim ├─┬─►│ hackrf_transfer ├───▲│ hackrf one ├────────────►│ 30db at │►│ 30db at │►│ DC blk ├─►│ ublox neo m9v/m8n  ├─┬─►│ ublox ucenter │
  └─────────────┘ │  └─────────────────┘   ◄└─────────▲──┘             └─────────┘ └─────────┘ └────────┘  └────────────────────┘ │  └───────────────┘
                  │                        │ ▲        │                                                                           │
                  │  ┌────────────────┐    │ │    ┌───┴──┐                                                                        │  ┌────────────┐  ┌────────┐
                  └─►│ hackrf android ├────┘ │    │ txc0 │                                                                        └─►│ linux gpsd ├─►│ marble │
                     └────────────────┘      │    └──────┘                                                                           └────────────┘  └────────┘
                                             │
  ┌───────────────────┐                      │
  │ multi-sdr-gps-sim ├──────────────────────┘
  └───────────────────┘
  ```
- TX gains - I tried multiple so that I see satellites with SNR around 30 to 55 dB. And tried to skip one 30 dB attenuator.
- I have TXC0 installed and HackRF should know about that and hopefully use it.

- I also tried multiple sample rates e.g.
  ```
  ./gps-sdr-sim -b 8 -e brdc2480.23n -s 13000000 -l 39.01973077309149,125.75254486374945,42.0 -o pyongyang.bin
  ```
  ```
  hackrf_transfer -t pyongyang.bin -f 1575420000 -s 13000000 -a 0 -x 0 -R
  ```
- I also tried to play with ppm correction, but when I try more than +-1 ppm, I'm not getting fix at all or loosing more often.

And now, I'm quite out of ideas what else to try.

## Issues

In any configuration I tried, I'm able to get 3D fix. However, the position is always drifting quite a lot (see pic). Usually after cold start, I get right position, which holds for a few minutes. But then it starts to walk around expected position in both static and dynamic modes.  Sometimes, I also lose fix. Altitude is almost always wrong. When I repeat the same simulation, the drift is always different.

![enter image description here](http://joelm.joja.cz/cb.png)

## Questions

1. I'm not expert in GPS nor RF, but... Can this be caused by bad clock source (it is probably some Chinese xtal on that board)? How can I verify, that I'm using the external crystal?
2. Could it be HackRF hardware problem? Since the drift is not dependent on input data and I tried multiple data sources as well as receivers...
3. Have you any other idea what can I try?

### What operating systems are you seeing the problem on?

Linux, Android, (Windows)

### What is the output of ```hackrf_info```?

```
$ hackrf_info
hackrf_info version: 2023.01.1
libhackrf version: 2023.01.1 (0.8)
Found HackRF
Index: 0
Serial number: 0000000000000000675c62dc326875cf
Board ID Number: 4 (HackRF One)
Firmware Version: 2023.01.1 (API:1.07)
Part ID Number: 0xa000cb3c 0x00614353
Hardware Revision: r9
Hardware appears to have been manufactured by Great Scott Gadgets.
Hardware supported by installed firmware:
    HackRF One
$ hackrf_clock -i
CLKIN status: clock signal detected
```

### Are you using any third-party software?

gps-sdr-sim,  multi-sdr-gps-sim

### Are you using any third-party hardware?

ublox gps modules, 2× 30dB attenuator, DC blocker

**Comment by martinling** [comment]
The `hackrf_clock -i` output you posted shows that the external CLKIN signal is being used.

We can't provide specfic support for gps-sdr-sim or GNSS simulation in general, but here are some thoughts:

Firstly, I note that you have appropriate attenuators, but you should also be shielding the whole test setup if you aren't already. GNSS signals are very weak and even the signal leakage from the hardware may be sufficient to cause interference to nearby devices.

The performance of this setup will be very sensitive to the stability of the specific TCXO used. Even if the reference clock is very good, the PLLs in both the MAX2837 and RFFC5072 will add some phase noise to the output and I would not expect a perfect result. You may want to try different TCXOs. There are some surplus 10MHz OCXO modules on the market which may be worth looking at too.

The state estimation algorithm in the GPS module will be making some attempt to model its own oscillator drift processes. It will be assuming in its modelling that the signal originates from a satellite with a near-perfect atomic clock. When it sees the received signal drifting by more than it expects from its own oscillator, it is therefore likely to be strongly biased towards interpreting that as due to movement of the receiver.

So phase noise in the signal will appear as random doppler shifts of the signal, and thus apparent velocity in the state estimate. This gives rise to the movement you see. The more stable the clock, the less error you should see, but there will be a limit to what can be achieved in practice.
