### ISSUE TITLE
hackrf_info

### ISSUE THREAD

**Issue by ejweng0428** [greatscottgadgets/hackrf#1429]
### What would you like to know?

Does the current version Hakrfone show "Hardware appears to have been manufactured by Great Scott Gadgets" in hackrf_info?

**Comment by martinling** [comment]
Boards manufactured by Great Scott Gadgets will display this message.

If a board does not display this message it just means it wasn't built by us. The design is open source and there are other manufacturers building their own boards, as they are free to do under the terms of the license.

To see which hardware revision you have, look at the `Hardware Revision` in the output of `hackrf_info`. The current revision is r10, but this version has only just finished its first production, so the latest you will find on the market just now is r9.

However, there is no need to have the latest hardware revision. The hardware revisions are not "upgrades". All revisions of HackRF One have the same specifications. The differences between revisions are minor, and mostly only involve slight differences in which of multiple similar components were used, due to availability at the time of production.

We appreciate it when folks buy genuine Great Scott Gadgets products from one of our [authorized resellers](https://greatscottgadgets.com/wheretobuy/). It’s what allows us to keep developing and supporting open source hardware.
