### ISSUE TITLE
What is the element/component that limits the maximum bandwidth in RX or TX?

### ISSUE THREAD

**Issue by All3xJ** [greatscottgadgets/hackrf#1432]
### What would you like to know?

I know that to be able to transmit at wider bandwidth we need more energy/power. I'm just curious about what actually is limiting it. What component(s)/element(s) contraint/limit the max bandwidth?

For example, hackRF has a maximum TX bandwidth of 20MHz, what is limiting it to this bandwidth?

Is this for a legal reason? Or is it for a physical/power/electrical reason?

**Comment by martinling** [comment]
The constraint on the maximum transmitted bandwidth is the sample rate of the DAC.

The [Nyquist-Shannon sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) states that the sample rate must be at least twice the bandwidth of a signal to avoid aliasing.

In the case of a quadrature (I/Q) sampling system, the sample rate must be at least equal to the bandwidth of the signal.

The MAX5864 ADC/DAC in HackRF One is rated for a maximum sample rate of 22Msps. In practice the sample rate is limited to 20Msps, because this is the highest data rate that can be reliably sustained over a USB 2.0 High Speed interface.

To transmit with more bandwidth you would need a faster DAC to generate the baseband signal, and you would also need a faster interface to get the samples to the DAC. If you upgraded those elements (e.g. with a 40Msps+ DAC and a USB SuperSpeed interface) then you would also run into the bandwidth limits of the MAX2837/MAX2839 transceiver IC. The widest bandwidth this can handle is around 30MHz.

**Comment by All3xJ** [comment]
> The constraint on the maximum transmitted bandwidth is the sample rate of the DAC.
> 
> The [Nyquist-Shannon sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) states that the sample rate must be at least twice the bandwidth of a signal to avoid aliasing.
> 
> In the case of a quadrature (I/Q) sampling system, the sample rate must be at least equal to the bandwidth of the signal.
> 
> The MAX5864 ADC/DAC in HackRF One is rated for a maximum sample rate of 22Msps. In practice the sample rate is limited to 20Msps, because this is the highest data rate that can be reliably sustained over a USB 2.0 High Speed interface.
> 
> To transmit with more bandwidth you would need a faster DAC to generate the baseband signal, and you would also need a faster interface to get the samples to the DAC. If you upgraded those elements (e.g. with a 40Msps+ DAC and a USB SuperSpeed interface) then you would also run into the bandwidth limits of the MAX2837/MAX2839 transceiver IC. The widest bandwidth this can handle is around 30MHz.

thanks a lot for your answer. now I know a first element/component that it's limiting it. but now I ask you: since "MAX2837/MAX2839 transceiver IC" has a maximum TX bandwidth of 30MHz, what is limiting it to this bandwidth? Is this for a legal reason? Or is it for a physical/power/electrical reason?

It's basically the same question. I'm really curious about this.

**Comment by Sasszem** [comment]
@All3xJ Page 5 of [the datasheet of the IC](https://www.analog.com/media/en/technical-documentation/data-sheets/max2839.pdf) lists a table of baseband filter bandwidths ("RF Channel BW Supported by
Baseband Filter"). There are 16 different filter bandwidths to choose from 1.75 to 28 MHz. The reason for the limit is most likely that none of the intended applications of the IC requires more, so they just went with it.
